title: Paper Title
tagline: Author, Coauthor
# When building locally, put an empty string. Otherwise, put "/your-repo-name"
# (the "/" is important)
baseurl: "/viki"
# arXiv ID (as in "https://arxiv.org/abs/[arXiv id]")
arxiv: ""
repo:  "https://vaeriants.github.io/viki"

author:
  name: Contact name
  url: "https://google.com"

# Leave this as is
markdown: kramdown
